// Provenance: adapted from Ginkobaloba/draughts-lab web/scripts/pack.mjs at commit
// 0a5c5a0fe6cc3443565937a738509f5de9479b19 (Paradigm-owned, MIT). Kept: the
// esbuild builds, the size table with gzip -9 and sha256, dist/manifest.json,
// the loader-purity guard and the deterministic ustar + gzip release tarball.
// Changed: chess-lab entries, the onnxruntime-web wasm file copied next to the
// worker, brotli sizes, the model files and a size receipt (--receipt), a
// third-party notice file, and a dev-page bundle that is not released.
//
//   node scripts/pack.mjs [--models D:/chess-lab-data/export] [--receipt ../receipts/web-v1/bundle-size.json]
//
// dist/
//   chess-lab.js                 loader: the worker client (what a page imports up front)
//   chess-lab-worker.js          worker: onnxruntime-web (wasm backend), chess.js, encoder, core
//   ort-wasm-simd-threaded.wasm  the onnxruntime-web WebAssembly runtime, fetched by the worker
//   THIRD_PARTY_NOTICES.txt      licenses of the code that ships
//   manifest.json                name, version, commit, files with bytes, gzip and brotli bytes, sha256
//   dev.js                       the local dev page's bundle (not released)
// release/chess-lab-web-<version>.tgz   the shipped files under package/, deterministic
//
// Budgets (gzip -9 bytes; exit code 1 when over): see BUDGETS.
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import { brotliCompressSync, constants, gzipSync } from "node:zlib";
import * as esbuild from "esbuild";

const WEB_ROOT = fileURLToPath(new URL("..", import.meta.url));
const { values } = parseArgs({
  options: {
    models: { type: "string", default: process.env.CHESS_LAB_EXPORT ?? "D:/chess-lab-data/export" },
    receipt: { type: "string" },
  },
});

const GZIP_LEVEL = 9;
const WASM = "ort-wasm-simd-threaded.wasm";
// Guards set from the first measured build (receipts/web-v1/bundle-size.json) with headroom;
// they catch an accidental second runtime or a heavy import, they are not targets.
const BUDGETS = { "chess-lab.js": 15_000, "chess-lab-worker.js": 60_000, [WASM]: 4_000_000 };
const SHIPPED = ["chess-lab.js", "chess-lab-worker.js", WASM, "THIRD_PARTY_NOTICES.txt"];

const pkg = JSON.parse(readFileSync(join(WEB_ROOT, "package.json"), "utf8"));
const depVersion = (name) => JSON.parse(readFileSync(join(WEB_ROOT, "node_modules", name, "package.json"), "utf8")).version;
const dist = join(WEB_ROOT, "dist");
const release = join(WEB_ROOT, "release");
rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
mkdirSync(release, { recursive: true });

const shared = { bundle: true, format: "esm", target: "es2022", platform: "browser", minify: true, sourcemap: false, charset: "utf8", legalComments: "eof", logLevel: "warning" };
await esbuild.build({ ...shared, entryPoints: { "chess-lab": join(WEB_ROOT, "src/index.ts") }, outdir: dist });
const workerBuild = await esbuild.build({ ...shared, entryPoints: { "chess-lab-worker": join(WEB_ROOT, "src/worker.ts") }, outdir: dist, metafile: true });
await esbuild.build({ ...shared, entryPoints: { dev: join(WEB_ROOT, "src/dev.ts") }, outdir: dist });
const ortDist = join(WEB_ROOT, "node_modules/onnxruntime-web/dist");
copyFileSync(join(ortDist, WASM), join(dist, WASM));

// Which packages actually ended up in the worker (for the notices).
const bundled = new Set();
for (const input of Object.keys(workerBuild.metafile.inputs)) {
  const m = /node_modules\/((?:@[^/]+\/)?[^/]+)\//.exec(input.replaceAll("\\", "/"));
  if (m) bundled.add(m[1]);
}
const notice = [
  "Third-party code in the chess-lab browser bundle (chess-lab.js, chess-lab-worker.js, ort-wasm-simd-threaded.wasm).",
  "Generated by web/scripts/pack.mjs. The chess-lab code itself is licensed GPL-3.0 (see LICENSE in the repo).",
  "Packages below are the esbuild inputs. onnxruntime-web's file is pre-built and may inline its own JS dependencies",
  "(runtime tree: MIT, Apache-2.0, BSD-3-Clause, ISC; see docs/LICENSES.md).",
  "",
];
for (const name of [...bundled].sort()) {
  const p = JSON.parse(readFileSync(join(WEB_ROOT, "node_modules", name, "package.json"), "utf8"));
  notice.push(`== ${name} ${p.version} (${p.license}) ==`);
  const lic = ["LICENSE", "LICENSE.md", "LICENSE.txt"].map((f) => join(WEB_ROOT, "node_modules", name, f)).find(existsSync);
  if (lic) notice.push(readFileSync(lic, "utf8").trim());
  else if (name === "onnxruntime-web") {
    notice.push(
      "The npm package ships no LICENSE file. Its bundle header reads: \"ONNX Runtime Web v" + p.version + " / Copyright (c) Microsoft",
      "Corporation. All rights reserved. / Licensed under the MIT License.\" The same package provides ort-wasm-simd-threaded.wasm,",
      "which is compiled from ONNX Runtime and its native dependencies; their notices are in ThirdPartyNotices.txt of",
      "github.com/microsoft/onnxruntime at tag v" + p.version + " (VERIFY and ship that file before any public release).",
    );
  } else notice.push("(no LICENSE file in the package; see its package.json)");
  notice.push("");
}
writeFileSync(join(dist, "THIRD_PARTY_NOTICES.txt"), `${notice.join("\n")}\n`);

let commit = "unknown";
let dirty = null;
try {
  commit = execFileSync("git", ["rev-parse", "HEAD"], { cwd: WEB_ROOT, encoding: "utf8" }).trim();
  dirty = execFileSync("git", ["status", "--porcelain", "--untracked-files=no", "--", "."], { cwd: WEB_ROOT, encoding: "utf8" }).trim() !== "";
} catch {
  // not a git checkout
}

const sizes = (data) => ({
  bytes: data.length,
  gzipBytes: gzipSync(data, { level: GZIP_LEVEL }).length,
  brotliBytes: brotliCompressSync(data, { params: { [constants.BROTLI_PARAM_QUALITY]: 11, [constants.BROTLI_PARAM_SIZE_HINT]: data.length } }).length,
  sha256: createHash("sha256").update(data).digest("hex"),
});
const files = SHIPPED.map((name) => ({ name, ...sizes(readFileSync(join(dist, name))) }));

// Guard: the loader must not contain worker-only code (chess.js, onnxruntime-web).
const loader = readFileSync(join(dist, "chess-lab.js"), "utf8");
for (const marker of ["rnbqkbnr/pppppppp", "ort-wasm", "InferenceSession", "Microsoft"]) {
  if (loader.includes(marker)) {
    console.error(`loader contains worker-only code (${marker})`);
    process.exit(1);
  }
}

const manifest = {
  schema: "chess-lab/web-bundle/v1",
  name: pkg.name,
  version: pkg.version,
  protocol: 1,
  commit,
  dirty,
  gzip_level: GZIP_LEVEL,
  budgets_gzip_bytes: BUDGETS,
  files,
};
writeFileSync(join(dist, "manifest.json"), `${JSON.stringify(manifest, null, 1)}\n`);

// Deterministic ustar archive (fixed mtime, owner and mode), then gzip.
function tarEntry(name, data) {
  const h = Buffer.alloc(512);
  const put = (s, off, len) => h.write(s, off, len, "ascii");
  put(name, 0, 100);
  put("0000644\0", 100, 8);
  put("0000000\0", 108, 8);
  put("0000000\0", 116, 8);
  put(`${data.length.toString(8).padStart(11, "0")}\0`, 124, 12);
  put("00000000000\0", 136, 12);
  put("        ", 148, 8);
  put("0", 156, 1);
  put("ustar\0", 257, 6);
  put("00", 263, 2);
  let sum = 0;
  for (const b of h) sum += b;
  put(`${sum.toString(8).padStart(6, "0")}\0 `, 148, 8);
  const pad = Buffer.alloc((512 - (data.length % 512)) % 512);
  return Buffer.concat([h, data, pad]);
}
const entries = [...SHIPPED, "manifest.json"].map((n) => tarEntry(`package/${n}`, readFileSync(join(dist, n))));
const tar = Buffer.concat([...entries, Buffer.alloc(1024)]);
const tgzName = `chess-lab-web-${pkg.version}.tgz`;
const tgz = gzipSync(tar, { level: GZIP_LEVEL, mtime: 0 });
writeFileSync(join(release, tgzName), tgz);
const tgzSha = createHash("sha256").update(tgz).digest("hex");
writeFileSync(join(release, `${tgzName}.sha256`), `${tgzSha}  ${tgzName}\n`);

// Model files (never in git; read from the export directory when present).
let models = null;
const modelManifest = join(values.models, "manifest.json");
if (existsSync(modelManifest)) {
  const mm = JSON.parse(readFileSync(modelManifest, "utf8"));
  models = mm.models.map((m) => {
    const data = readFileSync(join(values.models, m.file));
    const s = sizes(data);
    if (s.sha256 !== m.sha256) throw new Error(`${m.file}: sha256 does not match its manifest`);
    return { id: m.id, file: m.file, rated: m.rated, ...s };
  });
}

let over = false;
const fmt = (n) => n.toLocaleString("en-US");
console.log(`file | bytes | gzip -${GZIP_LEVEL} | brotli q11 | budget (gzip) | sha256`);
for (const f of [...files, ...(models ?? []).map((m) => ({ ...m, name: `model ${m.id}: ${m.file}` }))]) {
  const budget = BUDGETS[f.name];
  const status = budget === undefined ? "-" : `${f.gzipBytes <= budget ? "ok" : "OVER"} (<= ${fmt(budget)})`;
  if (budget !== undefined && f.gzipBytes > budget) over = true;
  console.log(`${f.name} | ${fmt(f.bytes)} | ${fmt(f.gzipBytes)} | ${fmt(f.brotliBytes)} | ${status} | ${f.sha256}`);
}
console.log(`release/${tgzName} | ${fmt(tgz.length)} | - | - | - | ${tgzSha}`);

if (values.receipt) {
  const pick = (name) => files.find((f) => f.name === name);
  const runtime = ["chess-lab.js", "chess-lab-worker.js", WASM].map(pick);
  const sum = (list, k) => list.reduce((a, f) => a + f[k], 0);
  const fp32 = models?.find((m) => m.id === "fp32");
  const receipt = {
    schema: "chess-lab/web-bundle-size/v1",
    generator: "web/scripts/pack.mjs --receipt",
    commit,
    dirty,
    node: process.version,
    versions: { "onnxruntime-web": depVersion("onnxruntime-web"), "chess.js": depVersion("chess.js"), esbuild: depVersion("esbuild") },
    notes: [
      "bytes: file size; gzipBytes: gzip level 9; brotliBytes: brotli quality 11 (what a server sends depends on its compression settings).",
      "runtime = loader + worker + the onnxruntime-web wasm; first_move = runtime + the fp32 model (the rated file); first_move_by_model = runtime + each exported model (only fp32 is rated).",
      "The loader is fetched with the page; the worker, wasm and model only when a model is first loaded.",
    ],
    files,
    models,
    totals: {
      runtime: { bytes: sum(runtime, "bytes"), gzipBytes: sum(runtime, "gzipBytes"), brotliBytes: sum(runtime, "brotliBytes") },
      first_move: fp32 === undefined ? null : {
        bytes: sum(runtime, "bytes") + fp32.bytes,
        gzipBytes: sum(runtime, "gzipBytes") + fp32.gzipBytes,
        brotliBytes: sum(runtime, "brotliBytes") + fp32.brotliBytes,
      },
      first_move_by_model: Object.fromEntries((models ?? []).map((m) => [m.id, {
        rated: m.rated,
        bytes: sum(runtime, "bytes") + m.bytes,
        gzipBytes: sum(runtime, "gzipBytes") + m.gzipBytes,
        brotliBytes: sum(runtime, "brotliBytes") + m.brotliBytes,
      }])),
    },
  };
  const out = resolve(values.receipt);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, `${JSON.stringify(receipt, null, 1)}\n`);
  console.log(`receipt: ${out}`);
}
if (over) {
  console.error("size budget exceeded");
  process.exit(1);
}
